AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  EtlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.main.run_pipeline
      Runtime: python3.11
      Timeout: 900
      CodeUri: ../../
      Events:
        Daily:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
